services:
  draw-chat:
    image: nathan5471/draw-chat:latest
    container_name: draw-chat
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://postgres:password@postgres:5432/drawchat
      - JWT_SECRET=your_jwt_secret
    restart: unless-stopped
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRESS_PASSWORD=password
      - POSTGRESS_DB=drawchat
      - POSTGRESS_USER=postgress
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: